### PR TITLE
Issues/52

### PR DESCRIPTION
**Pull request by mrohban**
added `extract_subpopulations` function which uses k-means on both treatment and control single cell data to identify the subpopulations and assign each cell to those.

### CODE REVIEW

**Comment by mrohban** [comment]
updated the base master and there was no conflict.

**Review by shntnu — CHANGES_REQUESTED** [review]
Awesome! Can you update roxygen2 to 6.0.1 and rerun documentation?

**Comment by mrohban** [comment]
updated to the version 6.0.1 and re-ran `devtools::document()`.

**Comment by shntnu** [comment]
Great! It would need some bit of refactoring to avoid using CellProfiler specific terminology (e.g. `Metadata_*`) but that should be straightforward using the approach described in http://dplyr.tidyverse.org/articles/programming.html. We can pair program next week and get this done

**Pull request merged**
