### PR TITLE
Implement entropy based feature selection

### PR DESCRIPTION
**Pull request by mrohban**
Here is the entropy based feature selection, Marie investigated in her internship. It uses Rcpp and some other libraries to make it computationally more efficient.

### CODE REVIEW

**Comment by mrohban** [comment]
@shntnu  I'm really confused with this. I've reverted all the commits to see if the base has caused the problem (in the branch named as tmp). And I noticed it is the case. Do you have any idea, what is wrong that causes segmentation fault at the end of tests? (this doesn't happen when I check the package locally).

**Comment by shntnu** [comment]
@mrohban Does `devtools::check()` pass on your computer (for the `master` and `tmp` branches`)?

**Comment by mrohban** [comment]
@shntnu Yes, it passes for both.

**Comment by shntnu** [comment]
Ok - seems to be a travis issue. I have cleared the cache and am restarting
the build. Let's see what happens
https://travis-ci.org/cytomining/cytominer/builds/317344745

**Comment by shntnu** [comment]
I've restarted the builds after clearing the travis cache. This should fix it.

**Comment by mrohban** [comment]
Great, thanks!

**Comment by shntnu** [comment]
@mrohban I profiled this code and I think we should stick with an R implementation. There are some performance gains (130s vs 170s for k = 1500 dimensions), but even that goes away if you just use foreach and 4 cores (60s)

http://rpubs.com/shantanu/svd_entropy

Let me know what you think

**Comment by shntnu** [comment]
This PR was supplanted by https://github.com/cytomining/cytominer/pull/123

**Comment by shntnu** [comment]
The files from this branch are archived at https://github.com/broadinstitute/imaging_metric_comparison/blob/master/cytominer-issues-50.zip

**Pull request closed without merging**
