### PR TITLE
Contributing guideline and function documentation

### LINKED ISSUE #70: Document function signatures
@mcquin had said:
It would be nice to have information in the README or a contributing document which describes the standardized function signatures.

### PR DESCRIPTION
**Pull request by mcquin**
Resolves #70

I've added a [wiki page on contributing](https://github.com/cytomining/cytominer/wiki/Contributing) to `cytominer`. It also includes a high-level overview of the function standardization used by `aggregate`, `normalize`, etc. 

What do you think? Is anything unclear? @shntnu @cells2numbers

### CODE REVIEW

**Comment by cells2numbers** [comment]
Nice! Very good summary of the functionality of cytominer. It could be useful to give some examples for aggregate, normalize, variable_select and transform. Probably it is enough to link to the documentation. How can I do this?

**Review by cells2numbers — COMMENTED** [review]
see comment :)

**Comment by mcquin** [comment]
Great idea, @cells2numbers! I've added the examples from the function documentation to the page.

**Comment by cells2numbers** [comment]
awesome, thx @mcquin

**Comment by shntnu** [comment]
This looks great!

**Pull request merged**
